<?php

/**
 * Implements hook_ctools_plugin_directory().
 */
function csc_role_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_theme
 */ 
function csc_role_theme() {
    return array(

        'csc_role_item' => array(
          'render element' => 'element',
          'file' => 'plugins/content_types/csc_role.inc',
        ),
    );
}
