<?php
/**
 * Implements hook_permission().
 */
function ie8_redirect_permission() {
  return array(
    'configure ie8_redirect' => array(
      'title' => t('Administer IE8 Redirection'),
      'restrict access' => TRUE,
    ),
  );
}

function ie8_redirect_init(){
  $url = variable_get('ie8_redirect_url','');
  
  if(strpos($_SERVER['REQUEST_URI'], $url)) return;
  
  if($url){
    preg_match('/MSIE (.*?);/', $_SERVER['HTTP_USER_AGENT'], $matches);
  
    //Browser is IE
    if (count($matches)>1){
      $version = $matches[1];
      if($version<=8) drupal_goto($url);
    }  
  }
}

function ie8_redirect_form($form, &$form_state){
  $form['page_redirect'] = array(
    '#prefix' => '<p>Please enter the page where you would like to redirect users when their browsers are IE8 or less.</p>',
    '#type' => 'textfield',
    '#title' => t('Path'),
    '#default_value' => variable_get('ie8_redirect_url', ''),
    '#description' => t('Path to page you want to redirect, i.e.: content/ie8_page'),
    '#required' => true,
  );
  
  $form['settings_general']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  
  return $form;
}

function ie8_redirect_form_submit($form, &$form_state){
  $values = $form_state['values'];
  $url = $values['page_redirect'];
  
  if($url){
    variable_set('ie8_redirect_url', $url);
    drupal_set_message(t('Your configuration has been saved.'));
  }else{
    drupal_set_message(t('URL Path not found on the system. Please, try again'), 'error');
  }
}

/**
 * hook_menu
 */
function ie8_redirect_menu(){
  $items = array();
  $items['admin/config/system/ie8_redirect'] = array(
    'title' => t('IE8 Redirect'),
    'description' => t('Redirect site when user browser is IE8 or less'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ie8_redirect_form'),
    'access arguments' => array('configure ie8_redirect'),
  );
  
  return $items;
}
