<?php
/**
 * hook_views_pre_execute
 *  
 */ 
function view_modifier_views_pre_execute(&$view) {
   if( $view->name == 'events'){
    $related = arg(1);
    $show = arg(2);

    //Adds event date table
    $view->build_info['query']->join('field_data_field_event_date', 'fed', 'fed.entity_id=node.nid');
    $view->build_info['count_query']->join('field_data_field_event_date', 'fed', 'fed.entity_id=node.nid');
    
    //adds filter for past and future
    if($show){    
      if($show == 'past'){
        $view->build_info['query']->where('NOW() >= fed.field_event_date_value');
        $view->build_info['count_query']->where('NOW() >= fed.field_event_date_value');
      }else{
        $view->build_info['query']->where('NOW() < fed.field_event_date_value');
        $view->build_info['count_query']->where('NOW() < fed.field_event_date_value');
      }
    }
    
    //Adds order condition
    if($show == 'future'){
      $view->build_info['query']->orderBy('fed.field_event_date_value', 'ASC');
    }else{
      $view->build_info['query']->orderBy('fed.field_event_date_value', 'DESC');
    }
    
   }
   
   if( $view->name == 'event_calendar' && $view->current_display == 'block_3'){
      //echo "<p><b>GOTCHA!!</b></p>";
      //Adds event date table
      $view->build_info['query']->leftjoin('field_data_field_audience', 'faud', 'faud.entity_id=node.nid');
    
      $view->build_info['query']->where("node.type = 'event' OR (node.type = 'class' AND faud.field_audience_value = 'drop-in')");
   }
}