<?php
/**
 * Implements hook_menu().
 */
function csc_calendar_menu() {
    $items = array();
    $items['csc_calendar'] = array(
         'page callback'    => 'csc_calendar_page_ajax',
         'page arguments' => array('month'), // TODO: change this to a CSC site setting
         'access arguments' => array('access content'),
         'type'             => MENU_NORMAL_ITEM,
    );
    $items['api/csc/calendar/block'] = array(
         'page callback'    => 'csc_calendar_page_ajax',
         'page arguments' => array(4, 5),
         'access arguments' => array('access content'),
         'type'             => MENU_NORMAL_ITEM,
    );
    return $items;
}

function csc_calendar_init(){
  $path = drupal_get_path('module', 'csc_calendar'); 
  // This script is for the pagination on the calendar views.
  $script = "
    (function($){
    $(window).load(function(){
    $('body').on('click','#csc-popup-calendar ul.pager > li > a',function(e){          
      $(this).addClass('my_ajax-processed');
      var url = $(this).attr('href');
      $('#csc-popup-calendar').empty().html('<img src=\"/sites/all/modules/custom/csc_calendar/status-active.gif\" style=\"margin-left:50%;\">');        
      $('#csc-popup-calendar').load(url,'ajax=1',function() {
             Drupal.attachBehaviors('#csc-popup-calendar');
      });
      return false;
    });
    }); 
    })(jQuery);
  ";
  drupal_add_js($script, 'inline');
}


/**
 * page callbacks
 */

function csc_calendar_page_ajax($length='month', $week=FALSE) {
    $_SESSION['csc_calendar_type'] = $length;
    $type = 'event_calendar-block_' . $length;
    if ($length == 'week' && $week) {
        $type = 'event_calendar-block_week_other';
    }
    $view_select_form = drupal_get_form('csc_calendar_view_form', $length);
    echo  '<div id="csc-popup-calendar" class="' . $length . '"> ' . drupal_render($view_select_form) . csc_readblock_get($type, 'views') . '</div>';
    exit();
}

/**
 * Ajax week callback for when week is giving as parameter. Calls event_calendar-block_week_other view-display
 */
function csc_calendar_page_ajax_week_other() {
    $_SESSION['csc_calendar_type'] = 'week';
    $type = 'event_calendar-block_week_other';
    $view_select_form = drupal_get_form('csc_calendar_view_form', 'week');
    echo  '<div id="csc-popup-calendar" class="week"> ' . drupal_render($view_select_form) . csc_readblock_get($type, 'views') . '</div>';
    exit();
}

function csc_calendar_view_form($form, &$form_state, $type = 'month') {
    $form = array(
       '#attributes' => array('class' => 'csc-calendar-view-form'),
    );
    $form['view_select'] = array(
        '#type' => 'select',
        '#title' => t('View by'),
        '#options' => array(
            'day' => t('Day'),
            'week' => t('Week'),
            'month' => t('Month'),
            'year' => t('Year'),
            'list' => t('List'),
        ),
        '#default_value' => $type,
    );
    return $form;
}

function csc_calendar_views_post_render(&$view, &$output, &$cache) {
    $vname = $view->name;
    $display = $view->current_display;
    $mini = (!empty($_GET['mini'])) ? $_GET['mini'] : FALSE;
    dpm($display, $vname);
    if ($vname == 'event_calendar' && ($display == 'block_week' || $mini)) {
        dpm($mini, 'mini');
        $sstr = '/\/api\/csc\/calendar\/block\/week[^"]+"/';
        $repstr = '/api/csc/calendar/block/week/' . $mini . '"';
        $output = preg_replace($sstr, $repstr, $output);
        dpm("here");
    }
}