<?php
/**
 * Implements hook_menu().
 */
function csc_calendar_menu() {
    $items = array();

    $items['csc_calendar'] = array(
         'page callback'    => 'csc_calendar_page_ajax',
         'page arguments' => array(), // Default view TODO: change this to a CSC site setting
         'access arguments' => array('access content'),
         'type'             => MENU_NORMAL_ITEM,
    );
    $items['api/csc/calendar/block'] = array(
         'page callback'    => 'csc_calendar_page_ajax',
         'page arguments' => array(4, 5),
         'access arguments' => array('access content'),
         'type'             => MENU_NORMAL_ITEM,
    );

    $items['admin/config/csc/calendar'] = array(
      'title' => 'Calendar',
      'description' => 'Settings for the CSC Calendar plugin',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('csc_calendar_admin'),
      'access arguments' => array('administer csc settings'),  // in csc isotope
      'type' => MENU_LOCAL_TASK,
    );
    return $items;
}


function csc_calendar_admin() {
  $form = array();
  $form['csc_calendar_default'] = array(
    '#type' => 'textfield',
    '#title' => t('Default Calendar View'),
    '#default_value' => variable_get('csc_calendar_default', 'month'),
    '#size' => 50,
    '#description' => t("Default view for CSC calendar on home page"),
    '#required' => TRUE,
  );
  return system_settings_form($form);
}

function csc_calendar_init(){
  $path = drupal_get_path('module', 'csc_calendar');
  // This script is for the pagination on the calendar views.
  $script = "
    (function($){
    $(window).load(function(){
    $('body').on('click','#csc-popup-calendar ul.pager > li > a',function(e){
      $(this).addClass('my_ajax-processed');
      var url = $(this).attr('href');
      $('#csc-popup-calendar').empty().html('<img src=\"/sites/all/modules/custom/csc_calendar/status-active.gif\" style=\"margin-left:50%;\">');
      $('#csc-popup-calendar').load(url,'ajax=1',function() {
             Drupal.attachBehaviors('#csc-popup-calendar');
      });
      return false;
    });
    });
    })(jQuery);
  ";
  drupal_add_js($script, 'inline');
}


/**
 * page callbacks
 */

function csc_calendar_page_ajax($length=FALSE, $week=FALSE) {
    if (empty($length)) { $length = variable_get('csc_calendar_default', 'month'); }
    $_SESSION['csc_calendar_type'] = $length;
    $type = 'event_calendar-block_' . $length;
    if ($length == 'week' && $week) {
        $type = 'event_calendar-block_week_other';
    }
    $view_select_form = drupal_get_form('csc_calendar_view_form', $length);
    echo  '<div id="csc-popup-calendar" class="' . $length . '"> ' . drupal_render($view_select_form) . csc_readblock_get($type, 'views') . '</div>';
    exit();
}

/**
 * Ajax week callback for when week is giving as parameter. Calls event_calendar-block_week_other view-display
 */
function csc_calendar_page_ajax_week_other() {
    $_SESSION['csc_calendar_type'] = 'week';
    $type = 'event_calendar-block_week_other';
    $view_select_form = drupal_get_form('csc_calendar_view_form', 'week');
    echo  '<div id="csc-popup-calendar" class="week"> ' . drupal_render($view_select_form) . csc_readblock_get($type, 'views') . '</div>';
    exit();
}

function csc_calendar_view_form($form, &$form_state, $type = 'week') {
    $form = array(
       '#attributes' => array('class' => 'csc-calendar-view-form'),
    );
    $form['view_select'] = array(
        '#type' => 'select',
        '#title' => t('View by'),
        '#options' => array(
            'day' => t('Day'),
            'week' => t('Week'),
            'month' => t('Month'),
            'year' => t('Year'),
            /*'list' => t('List'),*/
        ),
        '#default_value' => $type,
    );
    return $form;
}

/**
 * Post Render of views for adjusting URLS to prev and next weeks in calendar week view
 * @param $view
 * @param $output
 * @param $cache
 */
function csc_calendar_views_post_render(&$view, &$output, &$cache) {
    // for Calendar week view adjust the URLS for next week to use the 'api/csc/calendar/block' menu item
    $vname = $view->name;
    $display = $view->current_display;
    if ($vname == 'event_calendar' && ($display == 'block_week' || $display == 'block_week_other')) {
        // for urls like: http://www.csc.localhost/api/csc/calendar/block/week/2018-W15?ajax=1&mini=2018-W16
        $sstr = '/\/api\/csc\/calendar\/block\/week\/\d+\-W\d+\?ajax=1\&amp;mini=([^"]+)"/';
        $repstr = '/api/csc/calendar/block/week/$1"';
        $output = preg_replace($sstr, $repstr, $output);
        // for urls like: http://www.csc.localhost/api/csc/calendar/block/week?&mini=2018-W16
        $sstr = '/\/api\/csc\/calendar\/block\/week\?[^m]*mini=([^"\&]+)[^"]*"/';
        $repstr = '/api/csc/calendar/block/week/$1"';
        $output = preg_replace($sstr, $repstr, $output);
        // for beginning week urls: http://www.csc-dev.uvawork.com/csc_calendar?mini=2018-W15
        $sstr = '/csc_calendar\?mini=(\d+\-W\d+)[^"]*"/';
        $repstr = 'api/csc/calendar/block/week/$1"';
        $output = preg_replace($sstr, $repstr, $output);
    }
}
