<?php
/**
 * Implements hook_ctools_plugin_directory().
 */
function csc_lists_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_theme
 */
function csc_lists_theme() {
    return array(
        'csc_lists_item' => array(
          'render element' => 'element',
        ),
    );
}

/**
 * Theme function
 */
function theme_csc_lists_item($var){
  $image = ($var['image']) ? theme_image_style(array('style_name' => 'csc_medium','path' => $var['image'], 'alt' => $var['title'], 'title' => $var['title'], 'width' => '', 'height' => ''  )) : '';

  $output = '<div class="list-item">';
  if( $image != '' ) {
    $output.= '<div class="list-item-image">';
    $output.= $image;
    $output.= '</div>';
  }
  $output.= '  <h3 class="list-item-title">'. $var['title'] .'</h3>';
  $output.= '  <div class="list-item-body">';
  $output.= '    <div class="list-item-teaser">';
  $output.= $var['teaser'];
  $output.= '    </div>';
  $output.= '  </div>';
  $output.= '</div>';

  $output = l($output, 'node/' . $var['nid'], array('html' => true));

  return $output;
}
