<?php
/**
 * Implements hook_ctools_plugin_directory().
 */
function csc_related_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_theme
 */ 
function csc_related_theme() {
    return array(
        'csc_related_events_item' => array(
          'render element' => 'element',
          'file' => 'plugins/content_types/csc_related_events.inc',
        ),
        'csc_related_organizations_item' => array(
          'render element' => 'element',
          'file' => 'plugins/content_types/csc_related_organizations.inc',
        ),
        'csc_related_activities_item' => array(
          'render element' => 'element',
          'file' => 'plugins/content_types/csc_related_activities.inc',
        ),
        'csc_related_people_item' => array(
          'render element' => 'element',
          'file' => 'plugins/content_types/csc_related_people.inc',
        ),
        'csc_related_research_item' => array(
          'render element' => 'element',
          'file' => 'plugins/content_types/csc_related_research.inc',
        ),
        'csc_related_classes_item' => array(
          'render element' => 'element',
          'file' => 'plugins/content_types/csc_related_classes.inc',
        ),
        'csc_related_initiatives_item' => array(
          'render element' => 'element',
          'file' => 'plugins/content_types/csc_related_initiatives.inc',
        ),
        'csc_related_news_item' => array(
          'render element' => 'element',
          'file' => 'plugins/content_types/csc_related_news.inc',
        ),
    );
}
